

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 700
BASE_WORLD_WIDTH = 1447
BASE_WORLD_HEIGHT = 1087

MAP_SCALE = 1.46
WORLD_WIDTH = int(BASE_WORLD_WIDTH * MAP_SCALE)
WORLD_HEIGHT = int(BASE_WORLD_HEIGHT * MAP_SCALE)

DAY_MAP_PATH = "assets/images/maps/day_map.png"
NIGHT_MAP_PATH = "assets/images/maps/night_map.png"
PLAYER_IMAGE_PATH = "assets/images/player/player.png"
NPC_IMAGE_FOLDER = "assets/images/npc"
EVIDENCE_IMAGE_PATH = "assets/images/evidence/evidence.png"

INTRO_AUDIO_PATH = "assets/sounds/intro.WAV"
OUTRO_AUDIO_PATH = "assets/sounds/outro.WAV"
DAY_SOUND_PATH = "assets/sounds/day.mp3"
NIGHT_SOUND_PATH = "assets/sounds/night.mp3"
SCANNER_SOUND_PATH = "assets/sounds/scanner.mp3"
KILL_SOUND_PATH = "assets/sounds/kill.mp3"
FPS = 60

# цвета
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (100, 220, 100)
RED = (220, 60, 80)

PLAYER_SIZE = 56
PLAYER_SPEED = 2
NPC_SIZE = 56
NPC_COLOR = (200, 180, 90)
INTERACTION_DISTANCE = 95
NPC_SPEED = 1

MAX_DAYS = 5
NPCS_PER_DAY = 5
VISION_LENGTH = 243
VISION_WIDTH = 135
VISION_COLOR = (255, 230, 90, 70)

SUSPICION_MAX = 100
SUSPICION_TIME = 2
EVIDENCE_SUSPICION_TIME = 10

DAY_SCREEN_FRAMES = 120
INTRO_TEXT_SPEED = 45
STORY_TEXT_SPEED = 16

PANEL_COLOR = (25, 25, 25)
PANEL_BORDER = (220, 220, 220)

DAY = "ДЕНЬ"
NIGHT = "НОЧЬ"

EVIDENCE_SIZE = 27
EVIDENCE_COLOR = (180, 40, 40)
